#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd

from model_security_gate.adapters.yolo_ultralytics import UltralyticsYOLOAdapter
from model_security_gate.detox.prune import save_ultralytics_model, zero_out_ranked_channels


def parse_args():
    p = argparse.ArgumentParser(description="Experimental soft-ablation of ranked suspicious Conv2d channels")
    p.add_argument("--model", required=True)
    p.add_argument("--channel-csv", required=True, help="channel_scan.csv generated by security_gate.py --channel-scan")
    p.add_argument("--out", default="runs/pruned_model.pt")
    p.add_argument("--top-k", type=int, default=50)
    p.add_argument("--min-score", type=float, default=None)
    p.add_argument("--device", default=None)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    adapter = UltralyticsYOLOAdapter(args.model, device=args.device)
    df = pd.read_csv(args.channel_csv)
    zeroed = zero_out_ranked_channels(adapter, df, top_k=args.top_k, min_score=args.min_score)
    out = save_ultralytics_model(adapter, args.out)
    print(f"[DONE] zeroed {len(zeroed)} channels")
    print(f"[DONE] saved: {out}")


if __name__ == "__main__":
    main()
